name: Deploy to AWS

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1' # specify your region

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "latest"

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22.2"

      - name: Install Op
        run: go install lesiw.io/op@latest

      - name: Upload Docker Image to ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 915898657279.dkr.ecr.us-east-1.amazonaws.com
          docker build -t melvin .
          docker tag melvin:latest 915898657279.dkr.ecr.us-east-1.amazonaws.com/melvin:latest
          docker push 915898657279.dkr.ecr.us-east-1.amazonaws.com/melvin:latest

      - name: Run Terraform
        run: |
          op tfapply
