name: Upload Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  build-and-upload-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1' # specify your region

      # - name: Build Docker Image
      #   run: docker build -t ${{secrets.DOCKER_USERNAME}}/melvin .

      # - name: Login and Push Docker Image
      #   env: 
      #     DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      #     DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      #   run: |
      #     echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      #     docker push ${{secrets.DOCKER_USERNAME}}/melvin

      - name: Upload Docker Image to ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 915898657279.dkr.ecr.us-east-1.amazonaws.com
          docker build -t melvin .
          docker tag melvin:latest 915898657279.dkr.ecr.us-east-1.amazonaws.com/melvin:latest
          docker push 915898657279.dkr.ecr.us-east-1.amazonaws.com/melvin:latest